# Generated by Django 4.1 on 2024-04-10 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rule'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rule',
            old_name='description',
            new_name='rules_json',
        ),
    ]
